#!/usr/bin/env sh

ventoyROOT=/opt/ventoy
Ventoy2DiskScriptName=Ventoy2Disk.sh
Ventoy2DiskScriptPath=$ventoyROOT/Ventoy2Disk.sh
ls -l $Ventoy2DiskScriptPath | grep -q "root $USER" || sudo chgrp $USER $Ventoy2DiskScriptPath
test -x $Ventoy2DiskScriptPath || sudo chmod g+x $Ventoy2DiskScriptPath

if cd $ventoyROOT;then
	if [ $(id -u) != 0 ];then
		if set -o | \grep -q xtrace.*on;then
			sudo bash -x ./$Ventoy2DiskScriptName "$@"
		else
			sudo ./$Ventoy2DiskScriptName "$@"
		fi
	else
		./$Ventoy2DiskScriptName "$@"
	fi
fi

sudo touch $ventoyROOT/log.txt
tac $ventoyROOT/log.txt | sed "/^#* Ventoy2Disk/q" | tac
