#!/usr/bin/env sh

architecture=$(uname -m)
case $architecture in
	x86_64) ;;
	i686) architecture=i386;;
	*) echo "=> Unsupported architecture.";exit;;
esac
ventoyROOT=/opt/ventoy
VentoyGUIScript=$ventoyROOT/VentoyGUI.$architecture

ls -l $VentoyGUIScript | grep -q "root $USER" || sudo chgrp $USER $VentoyGUIScript
test ! -x $VentoyGUIScript && sudo chmod g+x $VentoyGUIScript

if cd $ventoyROOT;then
	if [ $(id -u) != 0 ];then
		sudo ./$(basename $VentoyGUIScript) "$@"
	else
		./$(basename $VentoyGUIScript) "$@"
	fi
fi

tac $ventoyROOT/log.txt | sed "/^#* Ventoy2Disk/q" | tac
