@echo off

title Running %~nx0 ...
set utf16LogFile=%~dpn0_%computername%.utf16
set logFile=%~dpn0_%computername%.out

set tailTool=tail.exe
%tailTool% -h >nul 2>&1
set rc=%errorlevel%
if "%rc%"=="9009" (
	echo The %tailTool% tool is not present>&2
	exit/b %rc%
)

echo =^> Showing the log file: %utf16LogFile% in real time on the child window, it takes about one or two minutes ...

type nul> %utf16LogFile%

start "%utf16LogFile%: System Information" %comspec% /c "mode 1400,400 && tail -f %utf16LogFile% | sed "s/\x0//g"

call :wmic_info >> %utf16LogFile% 2>&1

echo =^> Press any key to close the log window ...
pause > nul
taskkill -im %tailTool% -f

echo =^> Converting %utf16LogFile% to ascii ...
sed "s/\x0//g;" %utf16LogFile% | sed "s/ *$//;" >> %logFile%

echo =^> Please, send the file %logFile% to us.
echo.
title Command Prompt
goto :eof

:wmic_info
	echo %time%
	echo =^> Basebord info. ...
	wmic baseboard list brief
	echo =^> Bios info. ...
	wmic bios list brief
	echo =^> CDROM info. ...
	wmic cdrom list brief
	echo =^> Computer info. ...
	wmic computersystem list brief
	echo =^> CPU info. ...
	wmic cpu get name,socketdesignation,maxclockspeed,numberofcores,numberoflogicalprocessors
	echo =^> CSPRODUCT info. ...
	wmic csproduct list brief
	echo =^> dcomapp info. ...
	wmic dcomapp list brief
	echo =^> Screen info. ...
	wmic desktopmonitor list brief
	echo =^> Diskdrive info. ...
	wmic diskdrive list brief
	echo =^> Environment info. ...
	wmic environment list brief
	echo =^> IDE Controller info. ...
	wmic idecontroller list brief
	echo =^> IRQ Controller info. ...
	wmic irq list brief
	echo =^> Lecteurs logiques :
	wmic logicaldisk list brief
	echo =^> Logon info. ...
	wmic logon list brief
	echo =^> Memphysical info. ...
	wmic memphysical list brief
	echo =^> Netuse info. ...
	wmic netuse list brief
	echo =^> nic info. ...
	wmic nic list brief
	echo =^> nicconfig info. ...
	wmic nicconfig where ipenabled='true' list brief
	echo =^> NTDomain info. ...
	wmic ntdomain list brief
	echo =^> Nteventlog info. ...
	wmic nteventlog list brief
	echo =^> OS info. ...
	wmic os list brief
	echo =^> Pagefile info. ...
	wmic pagefile
	echo =^> Partition info. ...
	wmic partition list brief
	echo =^> portconnector info. ...
	wmic portconnector list
	echo =^> Printer info. ...
	wmic printer list brief
	echo =^> Printerconfig info. ...
	wmic printerconfig list brief
	echo =^> printjob info. ...
	wmic printjob list brief
	echo =^> Process info. ...
	wmic process list brief
	echo =^> Quick Fix Engineering info. ...
	wmic qfe list brief
	echo =^> Service info. ...
	wmic service list brief
	echo =^> Share info. ...
	wmic share list brief
	echo =^> Sounddev info. ...
	wmic sounddev list brief
	echo =^> Startup info. ...
	wmic startup list
	echo =^> Sysaccount info. ...
	wmic sysaccount list brief
	echo =^> Sysdriver info. ...
	wmic sysdriver list brief
	echo =^> Systemenclosure info. ...
	wmic systemenclosure list brief
	echo =^> Temperature info. ...
	wmic temperature list brief
	echo =^> Timezone info. ...
	wmic timezone list
	echo =^> Voltage info. ...
	wmic voltage list brief
	echo =^> Product info. ...
	wmic product list brief
	echo =^> softwarefeature info. ...
	wmic softwarefeature get Caption,ProductName,Version
	echo %time%
	goto :eof

