#!/usr/bin/env bash

function podman {
	local args=("$@")
	local firstArg=$1

	case $firstArg in
		pull)
			shift
			echo http_proxy=http://10.10.30.90:80 https_proxy=http://10.10.30.90:80 podman pull "${args[@]}"
		;;
		*) command podman "${args[@]}"
		;;
	esac
}

podman "$@"
