#!/usr/bin/env bash

function podman {
	local args=("$@")
	local firstArg=$1
	local podman=$(which -a podman | grep -v /usr/local/ -m1)

	case $firstArg in
		pull)
			shift
			echo env http_proxy=http://10.10.30.90:80 https_proxy=http://10.10.30.90:80 $podman pull "${args[@]}"
		;;
		*) $podman "${args[@]}"
		;;
	esac
}

podman "$@"
