#!/usr/bin/env bash

function podman {
	local args=("$@")
	local firstArg=$1
	local podman=$(which -a podman | grep -v /usr/local/ -m1)

	case $firstArg in
		pull)
			shift
			env http_proxy=$http_proxy https_proxy=$https_proxy $podman pull "${args[@]}"
		;;
		*) $podman "${args[@]}"
		;;
	esac
}

podman "$@"
